[3.2] SnapshotManager#getHighestBlockAt, PathValidationContext now holds the absolute start and target and bStats can now be deactivated
olijeffers0n/PatheticAPI pull request #103
Opened 2024-10-07 17:04 UTC by Metaphoriker

^

2024-10-07 17:12 UTC, olijeffers0n requested changes

2024-10-07 17:12 UTC, olijeffers0n commented on pathetic-model/src/main/java/org/patheloper/model/snapshot/FailingSnapshotManager.java
> +      int chunkX = position.getBlockX() & 0xF;
Ideally I’d prefer these to be shifts rather than masks, but up to you

2024-10-07 17:12 UTC, olijeffers0n commented on pathetic-model/src/main/java/org/patheloper/model/snapshot/FailingSnapshotManager.java
> +      for (int y = chunkSnapshot.getHighestBlockYAt(chunkX, chunkZ);
Hmm, could we make this some sort of binary search instead?

2024-10-07 17:18 UTC, Metaphoriker commented on pathetic-model/src/main/java/org/patheloper/model/snapshot/FailingSnapshotManager.java
> +      for (int y = chunkSnapshot.getHighestBlockYAt(chunkX, chunkZ);
how do you imagine that?

2024-10-07 17:21 UTC, olijeffers0n commented on pathetic-model/src/main/java/org/patheloper/model/snapshot/FailingSnapshotManager.java
> +      for (int y = chunkSnapshot.getHighestBlockYAt(chunkX, chunkZ);
Ignore me…

2024-10-08 07:59 UTC, olijeffers0n approved these changes

2024-10-08 07:59 UTC, merged