1.18.2 support and some fixes.
olijeffers0n/PatheticAPI pull request #61
Opened 2024-03-04 15:17 UTC by GodCipher

2024-03-04 18:07 UTC, aematsubara commented
Of course, go ahead!

2024-03-04 18:10 UTC, olijeffers0n requested changes, later dismissed
Thanks! Before I would merge this I would be interested in if it would be possible to add support for the versions which were previously supported. Thanks for this though!

2024-03-04 19:56 UTC, aematsubara commented
> Thanks! Before I would merge this I would be interested in if it would be possible to add support for the versions which were previously supported. Thanks for this though!

Sure, I think I found a solution for 1.15 & 1.16; is there a reason why versions 1.13 and 1.14 do not have an NMS implementation? I can add them if necessary

2024-03-04 20:05 UTC, olijeffers0n commented
> > Thanks! Before I would merge this I would be interested in if it would be possible to add support for the versions which were previously supported. Thanks for this though!
> 
> Sure, I think I found a solution for 1.15 & 1.16; is there a reason why versions 1.13 and 1.14 do not have an NMS implementation? I can add them if necessary
> 
> The reason why I used NMS to get the BlockState: [b03d20b#r139351123](https://github.com/patheloper/pathetic/commit/b03d20b3ab87bb89f0041b7b4a6df61e73f9bb95#r139351123)

They don’t have NMS versions because we simply only supported the major versions. If you are happy to implement them they will be approved 😄

2024-03-05 09:05 UTC, bsommerfeld commented on pathetic-nms/v1_18_R2/pom.xml
> +        <version>2.3</version>
This needs to be increased to 2.4. Unfortunately, we have already upgraded the versions in our trunk, so that 2.3 can no longer be resolved.

2024-03-05 10:35 UTC, olijeffers0n approved these changes

2024-03-05 10:47 UTC, merged

2024-03-05 10:47 UTC, GodCipher commented
Thanks for contributing tho!